---
title: "Checking the GPU condition on CnetOS7"
author: 
- name: Satoshi Kume
  email: satoshi.kume.1984@gmail.com
date: "`r Sys.Date()`"
graphics: no
package: rMiW
output:
    BiocStyle::html_document:
        toc_float: false
vignette: >
    %\VignetteIndexEntry{Checking the GPU condition on CnetOS7}
    %\VignetteIndexEntry{rMiW}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("rMiW_GPU.Rmd")$mtime`<br />
**Compiled**: `r date()`

Run the following commands after the installation of CUDA on CentOS.

# Check the package version

```{r echo=TRUE, eval=FALSE}
packageVersion("keras")
packageVersion("tensorflow")

```

# Check the GPU conditions

```{r echo=TRUE, eval=FALSE}
system("nvidia-smi")

system("lspci | grep -i nvidia")
system("nvidia-smi -l")
system("nvidia-smi dmon -s pu -d 5")
```

# Session information {.unnumbered}
```{r sessionInfo, echo=FALSE}
sessionInfo()
```
