---
title: "rMiW: 02. rMiW & BioImageDbs for a workflow for microscopy-based image analysis and deep learning"
author: 
- name: Satoshi Kume
  email: satoshi.kume.1984@gmail.com
date: "`r Sys.Date()`"
graphics: no
package: rMiW
output:
    BiocStyle::html_document:
        toc_float: false
vignette: >
    %\VignetteIndexEntry{rMiW}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("rMiW_02_BioImageDbs.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

```{r echo=TRUE, eval=FALSE}
#Install BioImageDbs
#BiocManager::install("ExperimentHub", force = TRUE)
#BiocManager::install("BioImageDbs", force = TRUE)

#Load packages
library(ExperimentHub)
library(BioImageDbs)
library(rMiW)

##Optional
#Removes all files in a cache file directory
#install.packages("R.cache")
#R.cache::clearCache("ExperimentHub")
```

# Obtain 2D image dataset via BioImageDbs

```{r echo=TRUE, eval=FALSE}
#Set the ExperimentHub function
eh <- ExperimentHub::ExperimentHub()

#Check LM_id0001
query(eh, c("BioImageDbs", "LM_id0001"))

#check 4d tensor of LM_id0001
(qr <- query(eh, c("BioImageDbs", "LM_id0001_DIC_C2DH_HeLa_4dTensor_Binary")))

#Download the dataset of LM_id0001 (LM_id0001_DIC_C2DH_HeLa_4dTensor_Binary.rds)
ImgData <- qr[[1]]
str(ImgData)

#Obtain Gif animation and view it
GifData <- qr[[2]]
magick::image_read(GifData)

```

#Create an U-NET-based model

```{r}
#Width, Height, Channels
ImgShape <- dim(ImgData$Train$Train_Original)[-1]
ImgShape
#[1] 512 512   1

#Create U-NET model
model <- unet2D_v01(shape = ImgShape)

#Vidualize the model
plot_model(model=model)
```

#Set compile parameters for 



```{r}
```

# Session information {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
