---
title: "rMiW: 2. rMiW & BioImageDbs to provide an analytical workflow for microscopy-based images and deep learning"
author: 
- name: Satoshi Kume
  email: satoshi.kume.1984@gmail.com
- name: Kozo Nishida
date: "`r Sys.Date()`"
graphics: no
package: knitr, magick
output:
    BiocStyle::html_document:
        toc_float: true
vignette: >
    %\VignetteIndexEntry{rMiW}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("rMiW_03_BioImageDbs.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

```{r echo=TRUE, eval=FALSE}
library(rMiW)
library(ExperimentHub)
library(BioImageDbs)
```

# Download 2D image dataset via BioImageDbs

```{r echo=TRUE, eval=FALSE}
library(rMiW)
library(ExperimentHub)
library(BioImageDbs)
```




# Session information {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
