---
title: "rMiW: 01. Providing a basic workflow for microscopy-based images"
author: 
- name: Satoshi Kume
  email: satoshi.kume.1984@gmail.com
date: "`r Sys.Date()`"
graphics: no
package: knitr, magick
output:
    BiocStyle::html_document:
        toc_float: true
vignette: >
    %\VignetteIndexEntry{rMiW}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r style, echo = FALSE, results = 'asis', message=FALSE}
BiocStyle::markdown()
```

**Last modified:** `r file.info("rMiW_01_Kidney.Rmd")$mtime`<br />
**Compiled**: `r date()`

# Getting started

```{r echo=TRUE, eval=FALSE}
library(rMiW)

```

# Import a kidney image from rMiW

The displayed image (`Mouse01_Kid_x20_z0_RR01.png') is an image of whole slide imaging (WSI) for observing the mouse P0 kidney tissue stained by H&E. 

```{r echo=TRUE, eval=FALSE}
options(EBImage.display = "raster")
file <- system.file("extdata", "Mouse01_Kid_x20_z0_RR01.png", package="rMiW")

#Visualization
EBImage::display(EBImage::resize(EBImage::readImage(files = file), w = 500))
```

```{r Fig001, out.width = '75%', fig.cap = "Mouse01_Kid_x20_z0_RR01.png", echo = FALSE}
options(EBImage.display = "raster")
file <- system.file("extdata", "Mouse01_Kid_x20_z0_RR01.png", package="rMiW")
img <- EBImage::resize(EBImage::readImage(files = file), w = 500)
EBImage::display(img)
```

# Basic image processing




# Session information {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```

